
server:
  port: 8112
  servlet:
    context-path: /digital-diary

#DNS seeding list connection string for MongoDB
spring:
  data:
    mongodb:
      uri: mongodb+srv://m001-student:m001-mongodb-basics@sandbox.hz9gs.mongodb.net/digital_diary?retryWrites=true&w=majority

#  security:
#    filter:
#      order: 10

springdoc:
  api-docs:
    path: /rest-api-docs
    enabled: true

  swagger-ui:
    path: /swagger-ui
    operationsSorter: method













