apiVersion: v1
kind: Service
metadata:
  name: digital-diary-service
spec:
  type: NodePort
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30009
  selector:
    app: digital-diary
    type: microservice-back-end